[package]
name = "catz"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.30.5"
clap = { version = "4.5.1", features = ["derive"] }
ratatui = "0.26.0"
crossterm = "0.27.0"
color-eyre = "0.6.3"
ctrlc = "3.4.2"
